import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/theme-provider"
import { SessionProvider } from "next-auth/react"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children , session }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <SessionProvider session={session}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
          <main>{children}</main>
          <Toaster />
          </ThemeProvider>
      </SessionProvider>
          </body>
    </html>
  )
}
